/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfileType = IDL.Variant({
  'Institution' : IDL.Null,
  'Industry' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'description' : IDL.Text,
  'profileName' : IDL.Text,
  'profileType' : ProfileType,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllIndustries' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllInstitutions' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getContactMessagesByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactMessage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfileType = IDL.Variant({
    'Institution' : IDL.Null,
    'Industry' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'description' : IDL.Text,
    'profileName' : IDL.Text,
    'profileType' : ProfileType,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllIndustries' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllInstitutions' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getContactMessagesByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };